### ISSUE TITLE
Portals Creating then Crashing

### ISSUE THREAD

**Issue by Aersaud** [trentech/ProjectPortals#104]
```
[23:36:48] [Server thread/INFO] [nucleus]: Aersaud ran the command: /portal save
[23:36:48] [Server thread/WARN] [pjp]: Can't find particle type for MINECRAFT:WITCH_SPELL
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]: org.h2.jdbc.JdbcSQLException: Hexadecimal string contains non-hex character: "{""ty                                                                                               pe"":""PORTAL"",""server"":""TheUnderWorld"",""rotation"":""east"",""price"":0.0,""properties"":{""particle"":""REDSTONE_DUST"",""color"":""BLUE"",""frame"":[""{\""world\"":\""                                                                                               TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-444.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{                                                                                               \""x\"":-444.0,\""y\"":72.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-444.0,\""y\"":73.0,\""z\"":672.0}}"",""{\""worl                                                                                               d\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-440.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vecto                                                                                               r3d\"":{\""x\"":-440.0,\""y\"":72.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-440.0,\""y\"":73.0,\""z\"":672.0}}"",""                                                                                               {\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-443.0,\""y\"":73.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",                                                                                               \""vector3d\"":{\""x\"":-441.0,\""y\"":73.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-442.0,\""y\"":73.0,\""z\"":672.                                                                                               0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-443.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""                                                                                               none\"",\""vector3d\"":{\""x\"":-442.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-441.0,\""y\"":71.0,\""z                                                                                               \"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-441.0,\""y\"":72.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""prese                                                                                               t\"":\""none\"",\""vector3d\"":{\""x\"":-442.0,\""y\"":72.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-443.0,\""y\"":7                                                                                               2.0,\""z\"":672.0}}""],""fill"":[""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-443.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-M                                                                                               adCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-442.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\                                                                                               "":-441.0,\""y\"":71.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-441.0,\""y\"":72.0,\""z\"":672.0}}"",""{\""world\"":                                                                                               \""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"":{\""x\"":-442.0,\""y\"":72.0,\""z\"":672.0}}"",""{\""world\"":\""TKM-MadCraft\"",\""preset\"":\""none\"",\""vector3d\"                                                                                               ":{\""x\"":-443.0,\""y\"":72.0,\""z\"":672.0}}""]}}"; SQL statement:
INSERT into `PORTALS` (Name, Data) VALUES (?, ?) -- (?1, ?2) [90004-196]
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.message.DbException.get(DbException.java:179)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.message.DbException.get(DbException.java:155)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.util.StringUtils.convertHexToBytes(StringUtils.java:943)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.value.Value.convertTo(Value.java:974)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.table.Column.convert(Column.java:167)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.command.dml.Insert.insertRows(Insert.java:143)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.command.dml.Insert.update(Insert.java:114)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.command.CommandContainer.update(CommandContainer.java:101)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.command.Command.executeUpdate(Command.java:260)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement                                                                                               .java:164)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:15                                                                                               0)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStat                                                                                               ement.java:61)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxy                                                                                               PreparedStatement.java)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at com.gmail.trentech.pjp.portal.PortalService.create(PortalService.java:162)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at com.gmail.trentech.pjp.portal.LegacyBuilder.build(LegacyBuilder.java:83)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at com.gmail.trentech.pjp.commands.portal.CMDSave.execute(CMDSave.java:48)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildC                                                                                               ommandElementExecutor.java:255)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispa                                                                                               tcher.java:341)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandMa                                                                                               nager.java:328)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer                                                                                               .java:958)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer                                                                                               .java:937)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile                                                                                               :37)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile                                                                                               :9)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:1                                                                                               49)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(Sour                                                                                               ceFile:539)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:2                                                                                               76)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.ja                                                                                               va:3977)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.j                                                                                               ava:396)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[23:36:48] [Server thread/INFO] [STDERR]: [org.h2.jdbc.JdbcSQLException:printStackTrace:80]:    at java.lang.Thread.run(Thread.java:748)
```

spongeforge-1.12.2-2655-7.1.0-BETA-3041.jar

**Comment by trentech** [comment]
Can't find particle type for MINECRAFT:WITCH_SPELL

This is case sensitive
