### ISSUE TITLE
crash server pls help

### ISSUE THREAD

**Issue by xXjojojXx** [trentech/ProjectPortals#118]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.4.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/9/19 11:33 AM
Description: Ticking block entity

java.lang.ExceptionInInitializerError
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at net.minecraft.world.chunk.Chunk.getUserFromId(Chunk.java:6021)
	at net.minecraft.world.chunk.Chunk.getValidatedUser(Chunk.java:5998)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(Chunk.java:5964)
	at net.minecraft.tileentity.TileEntity.getSpongeNotifier(TileEntity.java:2440)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:210)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2970)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zma000(WorldServer.java:2957)
	at net.minecraft.world.World.func_72939_s(World.java:6656)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2295)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Couldn't find a PluginContainer in the cause stack.
	at org.spongepowered.common.util.SpongeCatalogBuilder.lambda$build$0(SpongeCatalogBuilder.java:85)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.spongepowered.common.util.SpongeCatalogBuilder.build(SpongeCatalogBuilder.java:85)
	at org.spongepowered.common.data.SpongeKeyBuilder.build(SpongeKeyBuilder.java:45)
	at com.gmail.trentech.pjp.data.Keys.<clinit>(Keys.java:26)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at net.minecraft.world.chunk.Chunk.getUserFromId(Chunk.java:6021)
	at net.minecraft.world.chunk.Chunk.getValidatedUser(Chunk.java:5998)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(Chunk.java:5964)
	at net.minecraft.tileentity.TileEntity.getSpongeNotifier(TileEntity.java:2440)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:210)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2970)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zma000(WorldServer.java:2957)

-- Block entity being ticked --
Details:
	Name: ancientwarfareautomation:windmill_blade_tile // net.shadowmage.ancientwarfare.automation.tile.torque.multiblock.TileWindmillBlade
	Block type: ID #277 (tile.windmill_blade // net.shadowmage.ancientwarfare.automation.block.BlockWindmillBlade // ancientwarfareautomation:windmill_blade)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1172,115,-6), Chunk: (at 4,7,10 in 73,-1; contains blocks 1168,0,-16 to 1183,255,-1), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Actual block type: ID #277 (tile.windmill_blade // net.shadowmage.ancientwarfare.automation.block.BlockWindmillBlade // ancientwarfareautomation:windmill_blade)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:6656)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2295)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 4620601469177926741
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1340,69,-79), Chunk: (at 12,4,1 in 83,-5; contains blocks 1328,0,-80 to 1343,255,-65), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Level time: 76197787 game time, 76740629 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 64201 (now: false), thunder time: 15308 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjk000(MinecraftServer.java:3980)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Unknown Source)

**Comment by xXjojojXx** [comment]
pjc                      | 0.2.1                       | projectcore-7.0.0-0.2.1.jar
 pjp                      | 0.15.0                      | projectportals-7.1.0-0.15.0.jar

**Comment by TimPurdum** [comment]
Same issue, same crash, using same jars. Solved for now by uninstalling project portals.

---- Minecraft Crash Report ----
// Oops.

Time: 1/20/19 12:58 PM
Description: Ticking block entity

java.lang.ExceptionInInitializerError
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Optional.java:241)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at net.minecraft.world.chunk.Chunk.getUserFromId(SourceFile:5621)
	at net.minecraft.world.chunk.Chunk.getValidatedUser(SourceFile:5598)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(SourceFile:5564)
	at net.minecraft.tileentity.TileEntity.getSpongeNotifier(SourceFile:2857)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:210)
	at net.minecraft.world.WorldServer.updateTileEntity(SourceFile:2787)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlm000(SourceFile:2774)
	at net.minecraft.world.World.func_72939_s(SourceFile:4628)
	at net.minecraft.world.WorldServer.func_72939_s(SourceFile:2112)
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1625)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349)
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560)
	at net.minecraft.server.MinecraftServer.run(SourceFile:464)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Couldn't find a PluginContainer in the cause stack.
	at org.spongepowered.common.util.SpongeCatalogBuilder.lambda$build$0(SpongeCatalogBuilder.java:85)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.spongepowered.common.util.SpongeCatalogBuilder.build(SpongeCatalogBuilder.java:85)
	at org.spongepowered.common.data.SpongeKeyBuilder.build(SpongeKeyBuilder.java:45)
	at com.gmail.trentech.pjp.data.Keys.<clinit>(Keys.java:26)
	... 28 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Optional.java:241)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at net.minecraft.world.chunk.Chunk.getUserFromId(SourceFile:5621)
	at net.minecraft.world.chunk.Chunk.getValidatedUser(SourceFile:5598)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(SourceFile:5564)
	at net.minecraft.tileentity.TileEntity.getSpongeNotifier(SourceFile:2857)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:210)
	at net.minecraft.world.WorldServer.updateTileEntity(SourceFile:2787)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlm000(SourceFile:2774)

-- Block entity being ticked --
Details:
	Name: minecraft:enchanting_table // net.minecraft.tileentity.TileEntityEnchantmentTable
	Block type: ID #116 (tile.enchantmentTable // net.minecraft.block.BlockEnchantmentTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (258,66,67), Chunk: (at 2,4,3 in 16,4; contains blocks 256,0,64 to 271,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #116 (tile.enchantmentTable // net.minecraft.block.BlockEnchantmentTable)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(SourceFile:4628)
	at net.minecraft.world.WorldServer.func_72939_s(SourceFile:2112)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -6816321031835870216
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (90,64,130), Chunk: (at 10,4,2 in 5,8; contains blocks 80,0,128 to 95,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 239770283 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(SourceFile:4140)
	at net.minecraft.server.MinecraftServer.func_71230_b(SourceFile:838)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(SourceFile:319)
	at net.minecraft.server.MinecraftServer.run(SourceFile:480)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1090021536 bytes (1039 MB) / 1553989632 bytes (1482 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	Plugins: 
		Plugin{id=minecraft, name=Minecraft, version=1.12.2, description=Minecraft is a game about placing blocks and going on adventures, url=https://minecraft.net, authors=[Mojang], source=/Users/timpurdum/Desktop/SERVER2018/minecraft_server.1.12.2.jar}
		Plugin{id=sponge, name=Sponge, version=1.12.2-7.1.4, description=Shared code between SpongeForge and SpongeVanilla, url=https://www.spongepowered.org, source=/Users/timpurdum/Desktop/SERVER2018/spongevanilla-1.12.2-7.1.4.jar}
		Plugin{id=spongevanilla, name=SpongeVanilla, version=1.12.2-7.1.4, description=The SpongeAPI implementation for Vanilla Minecraft, url=https://www.spongepowered.org, source=/Users/timpurdum/Desktop/SERVER2018/spongevanilla-1.12.2-7.1.4.jar}
		Plugin{id=luckperms, name=LuckPerms, version=4.2.112, description=A permissions plugin, url=https://github.com/lucko/LuckPerms, authors=[Luck], source=mods/LuckPerms-Sponge-4.2.112.jar}
		Plugin{id=spongeapi, name=SpongeAPI, version=7.1.0-70763aa8, description=A Minecraft plugin API, url=https://www.spongepowered.org, source=/Users/timpurdum/Desktop/SERVER2018/spongevanilla-1.12.2-7.1.4.jar}
		Plugin{id=pjp, name=ProjectPortals, version=0.15.0, description=One stop shop for all things portal, url=http://github.com/TrenTech/ProjectPortals, authors=[TrenTech], source=mods/projectportals-7.1.0-0.15.0.jar}
		Plugin{id=pjc, name=ProjectCore, version=0.3.0, description=Core Libraries, url=http://github.com/TrenTech/ProjectCore, authors=[TrenTech], source=mods/projectcore-7.1.0-0.3.0.jar}
		Plugin{id=mcp, name=Mod Coder Pack, version=9.38, description=Modding toolkit to decompile and deobfuscate the Minecraft client and server files., url=http://www.modcoderpack.com/website/, authors=[Searge, ProfMobius, IngisKahn, Fesh0r, ZeuX, R4wk, LexManos, Bspkrs, Others], source=/Users/timpurdum/Desktop/SERVER2018/spongevanilla-1.12.2-7.1.4.jar}
		Plugin{id=pjw, name=ProjectWorlds, version=0.13.0, description=Multi world management plugin, url=http://github.com/TrenTech/ProjectWorlds, authors=[TrenTech], source=mods/projectworlds-7.1.0-0.13.0.jar}
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'SpongeVanilla'
	Type: Dedicated Server (map_server.txt)

**Comment by bloodmc** [comment]
This issue is caused by the Keys class not being initialized early. Simply calling Keys during `GamePreInitializationEvent` should solve the problem.

**Comment by trentech** [comment]
88478da1cbd0d74075d87151b2eba0d8e000e100
