### ISSUE TITLE
error connecting

### ISSUE THREAD

**Issue by llronaldoll** [trentech/ProjectPortals#120]
when creating a portal, I get this error when a player connects!

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.5.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/04/19 13:21
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at org.spongepowered.common.service.user.SpongeUserStorageService.getOrCreate(SpongeUserStorageService.java:78)
	at net.minecraft.entity.player.EntityPlayerMP.getUserObject(EntityPlayerMP.java:4045)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:158)
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:504)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Couldn't find a PluginContainer in the cause stack.
	at org.spongepowered.common.util.SpongeCatalogBuilder.lambda$build$0(SpongeCatalogBuilder.java:85)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.spongepowered.common.util.SpongeCatalogBuilder.build(SpongeCatalogBuilder.java:85)
	at org.spongepowered.common.data.SpongeKeyBuilder.build(SpongeKeyBuilder.java:45)
	at com.gmail.trentech.pjp.data.Keys.<clinit>(Keys.java:26)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at org.spongepowered.common.service.user.SpongeUserStorageService.getOrCreate(SpongeUserStorageService.java:78)
	at net.minecraft.entity.player.EntityPlayerMP.getUserObject(EntityPlayerMP.java:4045)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:158)
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:504)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjm000(MinecraftServer.java:3973)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3012651960 bytes (2873 MB) / 4146593792 bytes (3954 MB) up to 4146593792 bytes (3954 MB)
	JVM Flags: 2 total; -Xms4G -Xms4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2824 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version           | Source                               | Signature                                |
	|:------ |:--------------- |:----------------- |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2            | minecraft.jar                        | None                                     |
	| LCHIJA | mcp             | 9.42              | minecraft.jar                        | None                                     |
	| LCHIJA | FML             | 8.0.99.99         | forge.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2824      | forge.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | spongeapi       | 7.1.0-366290f8    | spongeforge-1.12.2-2768-7.1.5.jar    | None                                     |
	| LCHIJA | sponge          | 1.12.2-7.1.5      | spongeforge-1.12.2-2768-7.1.5.jar    | None                                     |
	| LCHIJA | spongeforge     | 1.12.2-2768-7.1.5 | spongeforge-1.12.2-2768-7.1.5.jar    | None                                     |
	| LCHIJA | economylite     | 2.15.1            | EconomyLite-7.1.0-2.15.1.jar         | None                                     |
	| LCHIJA | griefprevention | 1.12.2-4.3.0.689  | griefprevention-1.12.2-4.3.0.689.jar | None                                     |
	| LCHIJA | gwm_library     | 1.3.4             | GWMLibrary 1.3.4.jar                 | None                                     |
	| LCHIJA | gwm_crates      | 3.1.13            | GWMCrates 3.1.13.jar                 | None                                     |
	| LCHIJA | jobslite        | 1.8.1             | JobsLite-7.1.0-1.8.1.jar             | None                                     |
	| LCHIJA | langswitch      | 1.4               | LangSwitch-1.4.jar                   | None                                     |
	| LCHIJA | megamenus       | 0.3               | Mega Menus-0.3.jar                   | None                                     |
	| LCHIJA | pjc             | 0.2.1             | projectcore-7.0.0-0.2.1.jar          | None                                     |
	| LCHIJA | pjp             | 0.15.0            | projectportals-7.2.0-0.15.0 (1).jar  | None                                     |
	| LCHIJA | pjw             | 0.13.0            | projectworlds-7.2.0-0.13.0.jar       | None                                     |
	| LCHIJA | vshop           | 2.0               | VillagerShops-2.0.jar                | None                                     |
	| LCHIJA | yysscoreboard   | 0.2.0-pre         | YYSScoreboard-0.2.0-pre-b65.jar      | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2768-7.1.5.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Comment by trentech** [comment]
Please test with latest version.

**Comment by trentech** [comment]
https://github.com/trentech/ProjectPortals/issues/118

**Comment by llronaldoll** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.5.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 13/04/19 21:51
Description: Exception ticking world

java.lang.ExceptionInInitializerError
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at net.minecraft.world.chunk.Chunk.getUserFromId(Chunk.java:6021)
	at net.minecraft.world.chunk.Chunk.getValidatedUser(Chunk.java:5998)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(Chunk.java:5964)
	at org.spongepowered.common.event.tracking.IPhaseState.appendNotifierPreBlockTick(IPhaseState.java:749)
	at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:299)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2158)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Couldn't find a PluginContainer in the cause stack.
	at org.spongepowered.common.util.SpongeCatalogBuilder.lambda$build$0(SpongeCatalogBuilder.java:85)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.spongepowered.common.util.SpongeCatalogBuilder.build(SpongeCatalogBuilder.java:85)
	at org.spongepowered.common.data.SpongeKeyBuilder.build(SpongeKeyBuilder.java:45)
	at com.gmail.trentech.pjp.data.Keys.<clinit>(Keys.java:26)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239)
	at java.util.Optional.flatMap(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:135)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:304)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:122)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at net.minecraft.world.chunk.Chunk.getUserFromId(Chunk.java:6021)
	at net.minecraft.world.chunk.Chunk.getValidatedUser(Chunk.java:5998)
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(Chunk.java:5964)
	at org.spongepowered.common.event.tracking.IPhaseState.appendNotifierPreBlockTick(IPhaseState.java:749)
	at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:299)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:2158)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: Alfheim
	All players: 1 total; [EntityPlayerMP['llWinchesterll'/167, l='Alfheim', x=1304,70, y=43,50, z=-1770,70]]
	Chunk stats: ServerChunkCache: 537 Drop: 0
	Level seed: -1917575139105199221
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1324,21,-1905), Chunk: (at 12,1,15 in 82,-120; contains blocks 1312,0,-1920 to 1327,255,-1905), Region: (2,-4; contains chunks 64,-128 to 95,-97, blocks 1024,0,-2048 to 1535,255,-1537)
	Level time: 26684860 game time, 29199640 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 439 (now: true), thunder time: 85084 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjm000(MinecraftServer.java:3973)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3387551936 bytes (3230 MB) / 4030726144 bytes (3844 MB) up to 4030726144 bytes (3844 MB)
	JVM Flags: 2 total; -Xms4G -Xms4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2824 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                           | Version           | Source                            | Signature                                |
	|:------ |:---------------------------- |:----------------- |:--------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                    | 1.12.2            | minecraft.jar                     | None                                     |
	| LCHIJA | mcp                          | 9.42              | minecraft.jar                     | None                                     |
	| LCHIJA | FML                          | 8.0.99.99         | forge.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                        | 14.23.5.2824      | forge.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | spongeapi                    | 7.1.0-366290f8    | spongeforge-1.12.2-2768-7.1.5.jar | None                                     |
	| LCHIJA | sponge                       | 1.12.2-7.1.5      | spongeforge-1.12.2-2768-7.1.5.jar | None                                     |
	| LCHIJA | spongeforge                  | 1.12.2-2768-7.1.5 | spongeforge-1.12.2-2768-7.1.5.jar | None                                     |
	| LCHIJA | de_yottaflops_easyscoreboard | 2.5.1             | EasyScoreboards.jar               | None                                     |
	| LCHIJA | economylite                  | 2.15.1            | EconomyLite-7.1.0-2.15.1.jar      | None                                     |
	| LCHIJA | jobslite                     | 1.8.1             | JobsLite-7.1.0-1.8.1.jar          | None                                     |
	| LCHIJA | langswitch                   | 1.4               | LangSwitch-1.4 (1).jar            | None                                     |
	| LCHIJA | luckperms                    | 4.4.4             | LuckPerms-Sponge-4.4.4.jar        | None                                     |
	| LCHIJA | megamenus                    | 0.3               | Mega Menus-0.3.jar                | None                                     |
	| LCHIJA | placeholderapi               | 4.5.1             | PlaceholderAPI-4.5.1 (1).jar      | None                                     |
	| LCHIJA | pjc                          | 0.3.0             | projectcore-7.2.0-0.3.0.jar       | None                                     |
	| LCHIJA | pjp                          | 0.15.1            | projectportals-7.2.0-0.15.1.jar   | None                                     |
	| LCHIJA | pjw                          | 0.13.0            | projectworlds-7.2.0-0.13.0.jar    | None                                     |
	| LCHIJA | survival-games               | 1.2.0             | SurvivalGames-1.2.0.jar           | None                                     |
	| LCHIJA | vshop                        | 2.0-beta3         | VillagerShops-2.0-beta3.jar       | None                                     |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2768-7.1.5.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['llWinchesterll'/167, l='Alfheim', x=1304,70, y=43,50, z=-1770,70]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by trentech** [comment]
Try the development version on my Jenkins server

**Comment by llronaldoll** [comment]
works fine, however Particle are not set on restart server

**Comment by llronaldoll** [comment]
works fine, however

**Comment by llronaldoll** [comment]
@trentech works fine, however Particle are not set on restart server
