### ISSUE TITLE
Repport command: null

### ISSUE THREAD

**Issue by Heriptik** [trentech/ProjectPortals#125]
[Sponge]: Error occurred while executing command 'pjp:portal save' for source EntityPlayerMP['Pepefab'/6140, l='spawn', x=9943.14, y=166.20, z=12083.33]: null
21.06 16:55:42 [Server] INFO java.lang.NullPointerException: null
21.06 16:55:42 [Server] INFO at com.gmail.trentech.pjp.portal.PortalBuilder.build(PortalBuilder.java:98) ~[PortalBuilder.class:?]
21.06 16:55:42 [Server] INFO at com.gmail.trentech.pjp.commands.portal.CMDSave.execute(CMDSave.java:48) ~[CMDSave.class:?]
21.06 16:55:42 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.6-RC3616]
21.06 16:55:42 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.6-RC3616]
21.06 16:55:42 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.6-RC3616]
21.06 16:55:42 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.6-RC3616]
21.06 16:55:42 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]

**Comment by trentech** [comment]
I think there's something messed up with your config. Pastebin it please?
