### ISSUE TITLE
Error with /warp create

### ISSUE THREAD

**Issue by lasercar** [trentech/ProjectPortals#16]
```
[07:46:07] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'warp create hilltop' for source EntityPlayerMP['Lasercar7'/606, l='terra', x=-216.76, y=167.00, z=405.97]: org/spongepowered/api/data/persistence/DataTranslators
java.lang.NoClassDefFoundError: org/spongepowered/api/data/persistence/DataTranslators
	at com.gmail.trentech.pjp.utils.Serializer.serialize(Serializer.java:26) ~[Serializer.class:?]
	at com.gmail.trentech.pjp.data.object.Warp.create(Warp.java:44) ~[Warp.class:?]
	at com.gmail.trentech.pjp.commands.warp.CMDCreate.execute(CMDCreate.java:159) ~[CMDCreate.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) ~[CommandSpec.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2052-5.0.0-BETA-1680]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [SpongeCommandManager.class:1.10.2-2052-5.0.0-BETA-1680]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) [PacketUtil.class:1.10.2-2052-5.0.0-BETA-1680]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92-internal]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]
```
Versions:
![image](https://cloud.githubusercontent.com/assets/6022168/18265657/b00efd12-73cb-11e6-95df-c53659eee871.png)

**Comment by trentech** [comment]
This should be resolved upon re-downloading the development build
