### ISSUE TITLE
NPE on portal saving, SpongeVanilla

### ISSUE THREAD

**Issue by Time6628** [trentech/ProjectPortals#30]
Occurs after making a portal and filling it, and trying to save it.
```
[19:43:39] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'portal save' for source EntityPlayerMP['TimeTheCat'/1, l='hub1_10', x=-93.15, y=47.12, z=112.07]: null
java.lang.ExceptionInInitializerError
	at net.minecraft.world.WorldServer.spawnParticles(SourceFile:1796) ~[ls.class:?]
	at net.minecraft.world.WorldServer.spawnParticles(SourceFile:1787) ~[ls.class:?]
	at com.gmail.trentech.pjp.effects.Particle.spawnNonRepeat(Particle.java:95) ~[Particle.class:?]
	at com.gmail.trentech.pjp.effects.Particle.spawnParticle(Particle.java:65) ~[Particle.class:?]
	at com.gmail.trentech.pjp.portal.LegacyBuilder.build(LegacyBuilder.java:81) ~[LegacyBuilder.class:?]
	at com.gmail.trentech.pjp.commands.portal.CMDSave.execute(CMDSave.java:40) ~[CMDSave.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-6.0.0-BETA-149]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-6.0.0-BETA-149]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-6.0.0-BETA-149]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-6.0.0-BETA-149]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:825) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:812) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:123) [PacketUtil.class:1.10.2-6.0.0-BETA-149]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zio000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:140) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException: Cannot have a null object!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.10.2.jar:?]
	at org.spongepowered.api.event.cause.NamedCause.of(NamedCause.java:88) ~[NamedCause.class:1.10.2-6.0.0-BETA-149]
	at org.spongepowered.api.event.cause.NamedCause.source(NamedCause.java:57) ~[NamedCause.class:1.10.2-6.0.0-BETA-149]
	at net.minecraft.entity.Entity.handler$onConstructed$zmi000(SourceFile:51) ~[rw.class:?]
	at net.minecraft.entity.Entity.<init>(SourceFile:201) ~[rw.class:?]
	at net.minecraft.entity.item.EntityFireworkRocket.<init>(SourceFile:32) ~[zz.class:?]
	at org.spongepowered.common.effect.particle.SpongeParticleHelper.<clinit>(SpongeParticleHelper.java:123) ~[SpongeParticleHelper.class:1.10.2-6.0.0-BETA-149]
	... 26 more
```

**Comment by trentech** [comment]
If you updated from an older version make sure particle effects are up to date in the config. Easiest way is to delete the config and restart the server

**Comment by Time6628** [comment]
Didn't update, just installed it.

**Comment by JonathanxD** [comment]
Same

**Comment by Time6628** [comment]
This is a bug in SpongeVanilla itself, https://github.com/SpongePowered/SpongeVanilla/issues/275
closing this.
