### ISSUE TITLE
Error using command /pjp

### ISSUE THREAD

**Issue by Eufranio** [trentech/ProjectPortals#36]
```
[14:25:39] [Server thread/INFO] [nucleus]: PotterCraft_ ran the command: /pjp
[14:25:39] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'pjp' for source EntityPlayerMP['PotterCraft_'/243, l='Spawn', x=108.23, y=108.00, z=-85.72]: No value present
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_111]
        at com.gmail.trentech.pjp.commands.CMDPjp.execute(CMDPjp.java:60) ~[CMDPjp.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2171-5.1.0-BETA-2006]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2171-5.1.0-BETA-2006]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) [SpongeCommandManager.class:1.10.2-2171-5.1.0-BETA-2006]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) [PacketUtil.class:1.10.2-2171-5.1.0-BETA-2006]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by COLDYY1** [comment]
Hello Eufranio! 

I highly suggest you re-installing the actuall plugin itself. This could depend on the cached data that are stored. After the re-install, re-configure the desired settings in pjp.conf. And that should work fine. 

Best Regards,
COLDYY1

**Comment by trentech** [comment]
Resolved in latest release
