### ISSUE TITLE
java.lang.IllegalArgumentException: Data ID must be formatted correctly!

### ISSUE THREAD

**Issue by SjsolisZXA** [trentech/ProjectPortals#47]
**Sponge Forge Version:** spongeforge-1.11.2-2282-6.0.0-BETA-2297
**PJP Version:** projectportals-5.1.0-0.13.6

`[13:51:06] [Server thread/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=pjp, name=ProjectPortals, version=0.13.6, description=One stop shop for all things portal, url=http://github.com/TrenTech/ProjectPortals, authors=[TrenTech], source=C:\Users\Salva\Desktop\Sponge Servers\Official Sponge 1.11.2\mods\projectportals-5.1.0-0.13.6.jar}
java.lang.IllegalArgumentException: Data ID must be formatted correctly!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.11.2.jar:?]
        at org.spongepowered.common.data.SpongeDataRegistrationBuilder.manipulatorId(SpongeDataRegistrationBuilder.java:77) ~[SpongeDataRegistrationBuilder.class:1.11.2-2282-6.0.0-BETA-2297]
        at org.spongepowered.common.data.SpongeDataRegistrationBuilder.manipulatorId(SpongeDataRegistrationBuilder.java:45) ~[SpongeDataRegistrationBuilder.class:1.11.2-2282-6.0.0-BETA-2297]
        at org.spongepowered.common.data.SpongeDataManager.register(SpongeDataManager.java:255) ~[SpongeDataManager.class:1.11.2-2282-6.0.0-BETA-2297]
        at com.gmail.trentech.pjp.Main.onInitialization(Main.java:113) ~[Main.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_Main_onInitialization32.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-6.0.0-BETA-2297]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-6.0.0-BETA-2297]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345) [SpongeModEventManager.class:1.11.2-2282-6.0.0-BETA-2297]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:212) [SpongeMod.class:1.11.2-2282-6.0.0-BETA-2297]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:553) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:109) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by trentech** [comment]
projectportals-**_5.1.0_**-0.13.6
spongeforge-1.11.2-2282-**_6.0.0_**-BETA-2297

http://trentech.org/jenkins/job/Project%20Portals/

**Comment by trentech** [comment]
By the way. interaction permissions have changed in the 6.x builds. Be sure to check the help details in game which also work correctly now. Type `/hm portal create` for details. The effects all portal types
