### ISSUE TITLE
[1.11.2] Portals No Worky

### ISSUE THREAD

**Issue by alphawolf918** [trentech/ProjectPortals#81]
First command: /portal create SurvivalPortal world

*I build the portal frame*

Second command: /portal save

Then it throws an exception about some appending error:

org.spongepowered.api.event.cause.Cause$Builder.append... and so on.

Using latest build of all of your Project plugins (minus the inventory one because that one didn't work at all; it only prevented us from using our inventories) and the Forge version I'm using is slightly outdated but not by much.

**Comment by GlowTimeHD** [comment]
jep, got the same issue!

**Comment by alphawolf918** [comment]
Any update on this?

**Comment by truck0321** [comment]
Is this plugin not supported with spongeforge-1.11.2-2282-7.0.0-BETA-2376.jar mod?  I'm getting the same error.

**Comment by truck0321** [comment]
Here is the stack trace:
```
[21:40:38] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'portal save' for source EntityPlayerMP['dtruckenmiller'/779, l='world', x=168.30, y=64.00, z=238.75]: org.spongepowered.api.event.cause.Cause$Builder.append(Ljava/lang/Object;)Lorg/spongepowered/api/event/cause/Cause$Builder;
java.lang.NoSuchMethodError: org.spongepowered.api.event.cause.Cause$Builder.append(Ljava/lang/Object;)Lorg/spongepowered/api/event/cause/Cause$Builder;
	at com.gmail.trentech.pjp.portal.LegacyBuilder.build(LegacyBuilder.java:69) ~[LegacyBuilder.class:?]
	at com.gmail.trentech.pjp.commands.portal.CMDSave.execute(CMDSave.java:48) ~[CMDSave.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.11.2-2282-7.0.0-BETA-2376]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.11.2-2282-7.0.0-BETA-2376]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-2282-7.0.0-BETA-2376]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-2282-7.0.0-BETA-2376]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) ~[mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:153) ~[PacketUtil.class:1.11.2-2282-7.0.0-BETA-2376]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:159) [CauseTracker.class:1.11.2-2282-7.0.0-BETA-2376]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:152) [PacketUtil.class:1.11.2-2282-7.0.0-BETA-2376]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjk000(SourceFile:539) [fo$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:256) [SpongeImplHooks.class:1.11.2-2282-7.0.0-BETA-2376]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhj000(MinecraftServer.java:3946) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[21:40:49] [HikariPool-1 housekeeper/DEBUG] [com.zaxxer.hikari.pool.HikariPool/sponge]: HikariPool-1 - Pool stats (total=9, active=0, idle=9, waiting=0)
```

**Comment by trentech** [comment]
sponge 1.11.2 uses an old version of API 7.0.0, because changes to Cause builder was implemented. In other words, no It is not supported by latest versions, and I don't plan on adding support.

Try one of the older builds on Jenkins 

https://trentech.org/jenkins/job/ProjectPortals/
