### ISSUE TITLE
Wiki!?!?

### ISSUE THREAD

**Issue by Assassins88** [trentech/ProjectPortals#84]
Is there a wiki somewhere by saying how to create a bungee portal to another server?

I try this command:

/portal create SOEA lobby -c 23,64,289

and it comes the error: lobby is not loaded or does not exist

lobby is the name of the other server in bungee and the destination of the protal

**Comment by trentech** [comment]
/hm portal create

Your missing the -b flag

**Comment by Assassins88** [comment]
I know :)
Now I get an error when I go through the portal and get disconnected from the server.

`[14:03:16] [Server thread/WARN]: Failed to handle packet for /62.xxx.119.204:45672
java.util.NoSuchElementException: null
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285) ~[?:1.8.0_151]
	at java.util.ArrayDeque.pop(ArrayDeque.java:522) ~[?:1.8.0_151]
	at org.spongepowered.common.event.tracking.PhaseStack.pop(PhaseStack.java:77) ~[PhaseStack.class:1.12.2-2555-7.1.0-BETA-2840]
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:220) ~[PhaseTracker.class:1.12.2-2555-7.1.0-BETA-2840]
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:394) ~[PhaseContext.class:1.12.2-2555-7.1.0-BETA-2840]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zif000(NetHandlerPlayServer.java:2030) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]`

**Comment by trentech** [comment]
That's a new one. Have to investigate that one

**Comment by Assassins88** [comment]
But i tried to connect to a spigot server. I do not know if that is relevant.

**Comment by ylluminate** [comment]
I have to say, I second a wiki. It would be nice to see various examples and usecases of this.
