### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.gmail.trentech.pjp.data.Keys

### ISSUE THREAD

**Issue by JadenH** [trentech/ProjectPortals#89]
```
java.lang.NoClassDefFoundError: Could not initialize class com.gmail.trentech.pjp.data.Keys
	at com.gmail.trentech.pjp.data.mutable.LastLocationData$Builder.buildContent(LastLocationData.java:124)
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$1(DataUtil.java:183)
	at java.util.Optional.flatMap(Optional.java:241)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:183)
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:169)
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$0(DataUtil.java:150)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:150)
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)
	at org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:112)
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:212)
	at org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:96)
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)
	at org.spongepowered.common.service.user.SpongeUserStorageService.getOrCreate(SpongeUserStorageService.java:78)
	at net.minecraft.entity.player.EntityPlayerMP.getUserObject(EntityPlayerMP.java:3969)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:158)
	at net.minecraft.server.management.PlayerList.func_148545_a(PlayerList.java:503)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:135)
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```
Server is crashing with projectportals-7.1.0-0.14.2.jar

**Comment by trentech** [comment]
duplicate https://github.com/trentech/ProjectPortals/issues/86
